### ISSUE TITLE
Datenbestand säubern: nicht ZHdK accounts mit ZHdK E-mail Adressen

### ISSUE THREAD

**Issue by DrTom** [zhdk/leihs-server-inventory#1]
```
leihs=# SELECT count(*) FROM users WHERE email ilike '%zhdk.ch' AND organization <> 'zhdk.ch';
 count
-------
  1708
 ```

**Comment by DrTom** [comment]
Vorschlag Vorgehen: alle `*@zhdk.ch` Email Adressen, die nicht aus dem Sync kommen (Anzahl siehe oben), von der Primären Email in die sekundäre Email verschieben. 

Nebeneffekt: sign-in per `E-Mail` wird nicht mehr funktionieren. Da aber alle diese Accounts aus der Zeit vor dem E-Mail sign-in stammen sollten gibt es imho überhaupt kein Problem.

**Comment by eins78** [comment]
@DrTom small nitpick i remember from a previous query like this: this matches too many domains, it should at least be 

`SELECT count(*) FROM users WHERE email ilike '%@zhdk.ch' AND organization <> 'zhdk.ch';` (note the additional `@`).

It would match domains like `zhdk.ch.example.org` which is not a problem, but `netzhdk.ch` is also matched and used by the alumni (currently only one user, but still…)

**Comment by DrTom** [comment]
@eins78 OK noted

**Comment by nadjaweisskopf** [comment]
@DrTom ok, let's move them (with the criteria above "organization <> 'zhdk.ch") to the secondary email-adress.

**Comment by DrTom** [comment]
```
BEGIN TRANSACTION;
UPDATE users SET secondary_email = email WHERE organization = 'local' AND email ilike '%@zhdk.ch' AND secondary_email is  NULL;
UPDATE users SET email = NULL WHERE organization = 'local' AND email ilike '%@zhdk.ch'; 
END TRANSACTION;
```
