### ISSUE TITLE
Zusätzliche Benutzer aus ZAPI ins Leihs füttern

### ISSUE THREAD

**Issue by DrTom** [zhdk/leihs-server-inventory#2]
Siehe auch https://service.itz.zhdk.ch/otrs/index.pl?Action=AgentTicketZoom;TicketID=374004

* Derzeit ist `only_zhdk` aktiviert; diesen wegnehmen würde die anzahl der Benutzer etwa 20x vergrössern: no go. 
* Michi schlägt "Personen, die sich einloggen können vor"; das würde uns zur Zeit etwa 1000 Benutzer mehr bringen was kein Problem ist. Der Fall oben wäre damit abgedeckt. Mir scheint das auch gut kommunizierbar zu sein. 

Nadja, OK?

**Comment by DrTom** [comment]
Nadja hat OK gegeben.

**Comment by DrTom** [comment]
> so viel ich weiss, ist da nichts passiert; aktuell erstellt Tilo lokale accounts oder sagt dem vorgesetzten er solle ausleihen. ich denke nadja/Lukas sollten das anstossen und v.a. prüfen, ob das ok ist

@nadjaweisskopf FYI

**Comment by DrTom** [comment]
Mit Michi überprüfen ob das so umgesetzt werden kann.

**Comment by nadjaweisskopf** [comment]
@DrTom will as Michi what the effort would be. If not too big, then we'll go for solution 2.

**Comment by DrTom** [comment]
Die ZAPI Erweiterung wird umgesetzt werden. Das wird aber Zeit brauchen.

**Comment by DrTom** [comment]
See also https://github.com/zhdk/leihs-server-inventory/issues/2

**Comment by neoheat** [comment]
DevIn accepts the change. Governance check pending: https://pm.zhdk.ch/?controller=TaskViewController&action=show&task_id=49483

**Comment by neoheat** [comment]
Answer of Governance Check:
_Because the is the same process involved for students or employees, and because its only an extension of the group of people, there is no Governance check necessary_

**Comment by neoheat** [comment]
@DrTom DevIn has implemented the filter `has_account` into Z-API (Version 2), so this configuration change can be executed.


**Reminder after switch to `has_account` filter**
In the Z-API the filter `only_zhdk` and `has_account` is currently not enforced. After migrating Leihs to filter `has_account` enforcing has to be re-enabled.
