### ISSUE TITLE
AAI Rollover (dev only, not prod)

### ISSUE THREAD

**Issue by DrTom** [zhdk/leihs-server-inventory#3]
Dear Thomas Schank

The SAML certificate for the following SWITCHaai Resource will expire
in 42 days:

  Resource Name: leihs Switch AAI authentication
  Federation: SWITCHaai
  EntityID: https://aai.leihs.zhdk.ch/shibboleth
  Certificate Subject: CN=aai.leihs.zhdk.ch
  Valid From:  21. 01. 2019 15:05:11
  Valid Until: 20. 01. 2022 15:05:11

**Comment by DrTom** [comment]
We will not upgrade this anymore. There is now Switch OIDC. Add it somewhen in the future.

**Comment by neoheat** [comment]
@DrTom is this still an open task or is Leihs already using the OIDC?
